version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/ruby:2.7.2
      environment:
        PGHOST: 127.0.0.1
        PGUSER: postgres
        RAILS_ENV: test
        CI: 'true'
    - image: circleci/postgres:9.5-alpine
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: amiapi_test
        POSTGRES_PASSWORD: ""
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      - ruby/install-deps
      - run:
          name: wait for database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: setup database
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
      # - run:
      #     name: run unit tests
      #     command: bundle exec rails test
      - run:
          name: Run tests
          command: |
            bundle exec rake
            ./tmp/cc-test-reporter format-coverage -t simplecov -o tmp/codeclimate.test.json coverage/test/.resultset.json
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.test.json

  upload-coverage:
    <<: *defaults
    environment:
      CC_TEST_REPORTER_ID: 062a963965d6a7c348bb7a84158e15d973c2ba55eff1a7214d9bd149a471040f
    steps:
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json

workflows:
  version: 2
  commit:
    jobs:
      - build
      - test:
          requires:
            - build
      - upload-coverage:
          requires:
             - test
